site_name: calypr.github.io

plugins:
  - multirepo:
      cleanup: true

  - redirects:
      redirect_maps:
        'funnel/index.md': 'tools/funnel/index.md'

extra_css:
  - stylesheets/extra.css
  - termynal.css

extra_javascript:
  - javascripts/nav-open-level1.js
  - termynal.js

theme:
  logo: assets/logo.png
  custom_dir: overrides
  language: en
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - search.highlight
  palette:
    - scheme: default
      primary: custom

markdown_extensions:
  attr_list: {}
  md_in_html: {}
  admonition: {}
  termynal:
    title: bash
    buttons: macos
    prompt_literal_start:
      - $
  toc:
    permalink: true
  pymdownx:
    details: {}
    highlight:
      anchor_linenums: false
      line_spans: __span
      pygments_lang_class: true
    magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: calypr
      repo: calypr.github.io
    inlinehilite: {}
    snippets: {}
    superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
    tabbed:
      alternate_style: true

extra:
  generator: false
