title: GRIP

nav:
 - index.md
 - Database Configuration: docs/databases.md
 - Client Library: docs/clients.md
 - Jobs API: docs/jobs_api.md
 - Commands:
   - Server: docs/commands/server.md
   - Query: docs/commands/query.md
   - Create: docs/commands/create.md
   - Delete: docs/commands/delete.md
   - Drop: docs/commands/drop.md
   - List: docs/commands/list.md
   - MongoLoad: docs/commands/mongoload.md
   - ER: docs/commands/er.md
 - Queries:
   - Start a Traversal: docs/queries/traversal_start.md
   - Referencing Fields: docs/queries/jsonpath.md
   - Traverse the Graph: docs/queries/traverse_graph.md
   - Filtering: docs/queries/filtering.md
   - Record Transforms: docs/queries/record_transforms.md
   - Aggregation: docs/queries/aggregation.md
   - Output Control: docs/queries/output.md
   - Iteration: docs/queries/iterations.md
   - Jobs: docs/queries/jobs.md
 - GraphQL:
   - GraphQL: docs/graphql/graphql.md
   - Graph Schemas: docs/graphql/graph_schemas.md
 - Gripper:
   - Intro: docs/gripper/gripper.md
   - External Resource Proxies: docs/gripper/proxy.md
   - Graph Model: docs/gripper/graphmodel.md
 - Tutorials:
   - Amazon Purchase Network: docs/tutorials/amazon.md
   - Pathway Commons: docs/tutorials/pathway-commons.md
   - TCGA RNA Expression: docs/tutorials/tcga-rna.md
 - Security:
   - Basic Auth: docs/security/basic.md
