
nav:
- index.md
- getting-started
- Funnel:
  - funnel/*
- GRIP:
  - grip/*
- Git-DRS: []
- CALYPR:
  - Getting Started:
    - requirements.md
    - getting-started.md
    - Data Management:
      - data-management/git-drs.md
      - data-management/meta-data.md
      - data-model/integration.md
      - data-model/introduction.md
      - data-model/metadata.md
